### ISSUE TITLE
Exceptions in report component

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/MGX-gui#157]
For dataset SRR3569370 (which has no read-based analysis jobs) in MGX2_Unittest:

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "taxData" is null
	at de.cebitec.mgx.gui.report.ui.ReportSummaryTopComponent.createPieCharts(ReportSummaryTopComponent.java:695)
	at de.cebitec.mgx.gui.report.ui.ReportSummaryTopComponent.update(ReportSummaryTopComponent.java:661)
	at de.cebitec.mgx.gui.report.ui.ReportSummaryTopComponent.<init>(ReportSummaryTopComponent.java:113)
	at de.cebitec.mgx.gui.report.ui.ReportSummaryTopComponent.getDefault(ReportSummaryTopComponent.java:129)
	at de.cebitec.mgx.gui.report.ui.ReportAction.actionPerformed(ReportAction.java:46)
	at org.openide.awt.ContextAction$Performer.actionPerformed(ContextAction.java:446)
	at org.openide.awt.ContextAction$Performer.actionPerformed(ContextAction.java:442)
	at org.openide.awt.ContextManager.actionPerformed(ContextManager.java:263)
	at org.openide.awt.ContextAction.actionPerformed(ContextAction.java:106)
```

For dataset2, which has taxonomic classification, but no COG results:

```
java.util.NoSuchElementException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:758)
	at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:783)
	at org.knowm.xchart.internal.chartpart.AxisPair.overrideMinMaxForYAxis(AxisPair.java:409)
	at org.knowm.xchart.internal.chartpart.AxisPair.prepareForPaint(AxisPair.java:319)
	at org.knowm.xchart.internal.chartpart.AxisPair.paint(AxisPair.java:54)
	at org.knowm.xchart.CategoryChart.paint(CategoryChart.java:311)
	at org.knowm.xchart.XChartPanel.paintComponent(XChartPanel.java:168)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
```

**Comment by sjaenick** [comment]
todo: re-enable tooltips (related: https://github.com/knowm/XChart/issues/740)
and fix position of the 'no data' indicator
