### ISSUE TITLE
FileNotFoundException in Jobmonitor?

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/MGX-gui#17]
In gitlab by @sjaenick on Dec 10, 2014, 17:37

de.cebitec.mgx.client.exception.MGXServerException: java.io.FileNotFoundException: /vol/mgx-data/MGX_Stadtwerke/jobs/18.xml (No such file or directory)
	at de.cebitec.mgx.client.access.rest.RESTMethods.catchException(RESTMethods.java:125)
	at de.cebitec.mgx.client.access.rest.RESTMethods.get(RESTMethods.java:72)
	at de.cebitec.mgx.client.access.rest.JobAccess.BySeqRun(JobAccess.java:66)
	at de.cebitec.mgx.gui.controller.JobAccess.BySeqRun(JobAccess.java:200)

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Mar 11, 2015, 16:14

caused by old development bug; fixed.
