### ISSUE TITLE
KeggViewerTest

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/MGX-gui#34]
In gitlab by @sjaenick on Mar 11, 2015, 09:52

```
Running de.cebitec.mgx.gui.keggviewer.KeggViewerTest
regressionInterrupted
Mar 11, 2015 9:50:34 AM org.openide.util.Exceptions printStackTrace
SEVERE: null
de.cebitec.mgx.kegg.pathways.KEGGException: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "CONSTRAINT_INDEX_F ON PUBLIC.PATHWAY(MAPNUM) VALUES ('map07235', 480)"; SQL statement:
INSERT INTO pathway (mapnum, name) VALUES (?, ?) [23505-186]
	at de.cebitec.mgx.kegg.pathways.access.PathwayAccess.fetchAllFromServer(PathwayAccess.java:97)
	at de.cebitec.mgx.kegg.pathways.access.PathwayAccess.fetchall(PathwayAccess.java:58)
	at de.cebitec.mgx.kegg.pathways.access.PathwayAccess.getMatchingPathways(PathwayAccess.java:377)
	at de.cebitec.mgx.gui.keggviewer.KeggCustomizer$2.run(KeggCustomizer.java:94)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused by: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "CONSTRAINT_INDEX_F ON PUBLIC.PATHWAY(MAPNUM) VALUES ('map07235', 480)"; SQL statement:
INSERT INTO pathway (mapnum, name) VALUES (?, ?) [23505-186]
	at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1198)
	at de.cebitec.mgx.kegg.pathways.access.PathwayAccess.fetchAllFromServer(PathwayAccess.java:95)
	... 5 more
```

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Mar 11, 2015, 14:49

Status changed to closed by commit 934192b703ea2b66ccc6c0204555d974e2f92a68
