### ISSUE TITLE
Exception in search window

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/MGX-gui#4]
In gitlab by @sjaenick on Aug 19, 2014, 19:31

java.lang.ClassCastException: java.util.ArrayList cannot be cast to [Lde.cebitec.mgx.api.model.ObservationI;
	at de.cebitec.mgx.gui.search.ui.SearchTopComponent$VariableRowHeightRenderer.getTableCellRendererComponent(SearchTopComponent.java:457)
	at javax.swing.JTable.prepareRenderer(JTable.java:5736)

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Nov 9, 2014, 12:33

fixed
