### ISSUE TITLE
Assertion error in reference mapping components

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/MGX-gui#52]
In gitlab by @sjaenick on Nov 16, 2015, 17:06

```
WARNING [org.openide.windows.WindowManager]: [Winsys] TopComponent de.cebitec.mgx.gui.mapping.viewer.TopComponentViewer throws exception/error from its componentClosed() method.
Please repair it!
java.lang.AssertionError
	at de.cebitec.mgx.client.access.rest.MappingAccess.closeMapping(MappingAccess.java:73)
	at de.cebitec.mgx.gui.controller.MappingAccess.closeMapping(MappingAccess.java:129)
	at de.cebitec.mgx.gui.mapping.MappingCtx.close(MappingCtx.java:169)
	at de.cebitec.mgx.gui.mapping.viewer.TopComponentViewer.componentClosed(TopComponentViewer.java:190)
```

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Nov 20, 2015, 12:42

Status changed to closed by commit 11293613d72cbaac483a31b2a23e93bc0cc48adb

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Mar 10, 2017, 18:36

mentioned in commit a81fd99439c14b4c9b142b2360f5d80ccba60b9a

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Mar 10, 2017, 18:38

mentioned in commit 66cd8716e533eaf3d06ea137d977a062c76b79c7

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Mar 10, 2017, 18:39

mentioned in commit 05b166e075dbfd10727db5bef3633338f6cc988e

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Mar 10, 2017, 18:40

mentioned in commit 0ab0763f754409521639abf0e0107ec5e390f509
