### ISSUE TITLE
MAPlot Exception

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/MGX-gui#6]
In gitlab by @sjaenick on Aug 25, 2014, 13:13

java.lang.IndexOutOfBoundsException: toIndex = 2
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:962)
	at java.util.ArrayList.subList(ArrayList.java:954)
	at de.cebitec.mgx.gui.charts.basic.MAPlot.show(MAPlot.java:66)
	at de.cebitec.mgx.gui.attributevisualization.ui.ControlPanel.actionPerformed(ControlPanel.java:373)

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Aug 25, 2014, 15:35

Status changed to closed by commit 0e28ed
