### ISSUE TITLE
QualityEncoder issue

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/MGX-gui#80]
In gitlab by @sjaenick on Jun 21, 2016, 15:02

```
[#|2016-06-21T15:00:48.463+0200|SEVERE|glassfish3.1.2|de.cebitec.mgx.web.SeqRunBean|_ThreadID=134;_ThreadName=Thread-2;|java.lang.ArrayIndexOutOfBoundsException: -128
        at de.cebitec.mgx.seqstorage.encoding.QualityEncoder.decode(QualityEncoder.java:43)
        at de.cebitec.mgx.seqstorage.CSQFReader.getEntry(CSQFReader.java:192)
        at de.cebitec.mgx.seqstorage.CSQFReader.hasMoreElements(CSQFReader.java:129)
        at de.cebitec.mgx.web.SeqRunBean$1.run(SeqRunBean.java:239)
        at de.cebitec.mgx.executor.TransactionalExecutor.execute(TransactionalExecutor.java:23)

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Jun 21, 2016, 16:54

Title changed from **QualitEncoder issue** to **QualityEncoder issue**

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Jun 28, 2016, 21:18

Made the issue confidential

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Jul 10, 2016, 11:06

bug in fastq reader? maybe use
http://www.mcdonaldlab.biology.gatech.edu/bioinformatics/DetermineFastqQualityEncoding.pl
to determine correct encoding

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Jul 10, 2016, 11:27

http://onetipperday.sterding.com/2012/10/code-snip-to-decide-phred-encoding-of.html

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Sep 8, 2016, 07:34

QualityEncoder also needs some basic documentation how the encoding/decoding actually works.
