### ISSUE TITLE
Exception in JobNode.getParameterToolTip

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/MGX-gui#86]
In gitlab by @sjaenick on Jun 29, 2016, 14:41

```
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.parseLong(Long.java:631)
	at de.cebitec.mgx.gui.nodes.JobNode.getParameterToolTip(JobNode.java:95)
	at de.cebitec.mgx.gui.nodes.JobNode.<init>(JobNode.java:54)

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Jun 29, 2016, 18:55

Made the issue confidential

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Jun 29, 2016, 21:12

mentioned in commit ffe8f9b043a6e101ae08eb2d7586df3e477244b9

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Jul 13, 2016, 16:25

Changed title: **Exception** → **Exception{+ in JobNode.getParameterToolTip+}**

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Aug 31, 2016, 15:37

testcase: project MGX_Viersen, Run All_in_one_1_3

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Aug 31, 2016, 15:47

mentioned in commit 4ed98db081ec0de8fcfcf5e9c6b9f3c6f79751c4

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Mar 10, 2017, 18:01

mentioned in commit bfea895400017dfe9e4cfd432203ce2761a2fa3b

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Mar 10, 2017, 18:32

mentioned in commit bd060a8cd7775a33389c7ce2512a70f3aa330d92

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Mar 10, 2017, 18:33

mentioned in commit ceebcf7616a5f046e21dd3eb131a664be25371a4

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Mar 10, 2017, 18:34

mentioned in commit 176021361b16c39a643508af1de541870e16ac8d

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Mar 10, 2017, 18:42

mentioned in commit 6b502d2106be69a484d3fa52e5f770e346700121
