### ISSUE TITLE
Don't hold connection for a long time in upload#cancel()

### ISSUE THREAD

**Issue by sjaenick** [MGX-metagenomics/MGX-gui#97]
In gitlab by @sjaenick on Feb 19, 2017, 14:07

```
[#|2017-02-17T13:14:30.292+0100|WARNING|glassfish3.1.2|com.zaxxer.hikari.pool.ProxyLeakTask|_ThreadID=270345;_ThreadName=Thread-2;|Connection leak detection triggered for org.post
gresql.jdbc.PgConnection@190049b, stack trace follows
java.lang.Exception: Apparent connection leak detected
        at de.cebitec.mgx.upload.SeqUploadReceiver.cancel(SeqUploadReceiver.java:150)
        at de.cebitec.mgx.upload.UploadSessions.timeout(UploadSessions.java:89)
        at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1052)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1124)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:5388)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:619)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:49)
```

**Comment by sjaenick** [comment]
In gitlab by @sjaenick on Feb 21, 2017, 14:45

closed via commit e6232414faa9d49ad9eb4dc8c85592f9de90cf3c
